common/models/Orders.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "orders".
 *
 * @property int $id
 * @property string $customer_name
 * @property string $address
 * @property string $description Дополнительная информация к заказу
 *
 * @property Goods[] $goods
 */
class Orders extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'orders';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['customer_name', 'address', 'description'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'customer_name' => 'ФИО покупателя',
            'address' => 'Адрес',
            'description' => 'Дополнительная информация к заказу',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGoods()
    {
        return $this->hasMany(Goods::className(), ['order_id' => 'id']);
    }
}

backend/controllers/GoodsController.php
<?php

namespace backend\controllers;

use common\models\GoodsPhotos;
use common\models\UploadPhoto;
use Yii;
use common\models\Goods;
use common\models\search\Goods as GoodsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\BadRequestHttpException;
use yii\web\UploadedFile;

/**
 * GoodsController implements the CRUD actions for Goods model.
 */
class GoodsController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Goods models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new GoodsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Goods model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Goods model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Goods();
        $orderId = Yii::$app->request->get('order_id');
        $model->order_id = $orderId;

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['/order/update', 'id' => $orderId]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Goods model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        /** @var Goods $model */
        $model = $this->findModel($id);
        $model->order_id = Yii::$app->request->get('order_id');
        // Сохраняем товар и переходим обратно к форме редактирования заказа.
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /** Удаление фотографии из товара
     * @param integer $id  id Фото товара
     * @return \yii\web\Response
     */
    public function actionPhotoRemove($id)
    {
        /** @var  GoodsPhotos $model */
        $model = GoodsPhotos::find()->where(['id' => $id])->one();
        $product = $model->product;
        if(!empty($model)) {
            $filepath = yii::$app->params['photoPath'] . $model->filename;
            if (file_exists($filepath)) {
                unlink($filepath);
            }
            $model->delete();
            Yii::$app->session->setFlash('success', 'Фотография успешно удалена');
            return $this->redirect('/order/update?id=' . $product->order_id);
        }
        throw new BadRequestHttpException('Передано неверное значение статуса участника');
    }


    /** Добавить фото к товару
     * @param integer $id
     * @return \yii\web\Response
     */
    public function actionPhotoAdd($id)
    {
        $images = UploadedFile::getInstancesByName('UploadForm[photo]');
        $productId = (int)Yii::$app->request->post('id');
        if(!empty($images)){
            foreach ($images as $image){
                $model = new GoodsPhotos();
                $uploadForm = new UploadPhoto();
                $uploadForm->image = $image;
                $model->product_id = $productId;
                $model->filename = $uploadForm->uploadImage();
                if(!empty($model->filename)){
                    $model->save();
                }else{
                    foreach ($uploadForm->errors['image'] as $error)
                    Yii::$app->session->setFlash('danger', $error);
                }
            }
            Yii::$app->session->setFlash('success', 'Фотографии успешно сохранены');
        }
        return $this->redirect('/order/update?id='.$id);
    }

    /**
     * Deletes an existing Goods model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
        return $this->redirect(['index']);
    }

    /**
     * Finds the Goods model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Goods the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Goods::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/controllers/OrderController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Orders;
use common\models\search\Orders as OrdersSearch;
use common\models\search\Goods as GoodsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * OrderController implements the CRUD actions for Orders model.
 */
class OrderController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Orders models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new OrdersSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Orders model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Orders model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Orders();
        $isNew = $model->isNewRecord;
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['update', 'id' => $model->id]);
            //return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Orders model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $searchModel = new GoodsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->post(), $id);
        $dataProvider->pagination = ['pageSize' => 10];

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            //return $this->redirect(['view', 'id' => $model->id]);
            return $this->redirect(['/']);
        }

        return $this->render('update', [
            'model' => $model,
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);
    }

    /**
     * Deletes an existing Orders model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Orders model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Orders the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Orders::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/views/order/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\ListView;
use \yii\bootstrap\Modal;

/* @var $this yii\web\View */
/* @var $model common\models\Orders */
/* @var $form yii\widgets\ActiveForm */
/* @var $dataProvider yii\data\ActiveDataProvider*/

// $this->registerJsFile('/js/order.js');
?>

<div class="orders-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'customer_name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'address')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'description')->textInput(['maxlength' => true]) ?>

    <?php if(!$model->isNewRecord){ ?>
        <?php // Теперь список товаров со всеми фото размещаем?>
        <div>Товары в заказе:</div>
        <?=
        ListView::widget([
            'dataProvider' => $dataProvider,
            'summary' => false,
            'itemOptions' => ['class' => 'product'],
            'itemView' => '_product',
        ])
        ?>
        
        <?=Html::a('Добавить товар', '/goods/create?order_id='.$model->id)?>
    <?php } ?>



    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

<?php Modal::begin([
    'header' => '<h2>Загрузка фото</h2>',
    'id' => 'modal-upload-photos',
    //'toggleButton' => ['label' => 'Х'],
    //'footer' => '',
])?>
<?=Html::beginForm(['goods/photo-add', 'id'=>$model->id], 'post', ['enctype' => 'multipart/form-data'])?>
<?=Html::fileInput('UploadForm[photo][]', '', ['multiple'=>'multiple', 'class'=>'upload-photos'])?>
<?=Html::hiddenInput('id', '', ['class'=>'modal-upload-photos-id'])?>
<?=Html::submitButton('Загрузить')?>
<?=Html::endForm()?>
<?php Modal::end();?>

backend/views/order/_product.php
<?php
    use \yii\helpers\Html;
    use common\models\GoodsPhotos;
    /** @var common\models\Goods $model */
?>

<div>Артикул:<?=$model->id?>| <strong><?=$model->name?></strong></div>

<div>
    <?php /** @var GoodsPhotos $photo */
    foreach ($model->goodsPhotos as $photo){ ?>
        <span><?=Html::img('/photos/'. $photo->filename, ['width'=>'200'])?><?=Html::a('Удалить', '/goods/photo-remove?id='.$photo->id)?></span>
    <?php } ?>
</div>
<div><?=Html::a('Добавить фото', '#'.$model->id, ['data-id'=>$model->id, 'class'=>'upload-photos-link'])?></div>
<div><?=$model->desc?></div>
<hr/>

backend/views/order/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\search\Orders */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="orders-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'customer_name') ?>

    <?= $form->field($model, 'address') ?>

    <?= $form->field($model, 'description') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/order/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Orders */

$this->title = 'Create Orders';
$this->params['breadcrumbs'][] = ['label' => 'Orders', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="orders-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/order/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel common\models\search\Orders */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Orders';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="orders-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Orders', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'customer_name',
            'address',
            'description',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>


</div>

backend/views/order/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Orders */
/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var $searchModel common\models\search\Orders */

$this->title = 'Update Orders: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Orders', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="orders-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'dataProvider' => $dataProvider,
        'searchModel ' => $searchModel,
    ]) ?>

</div>

backend/views/order/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Orders */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Orders', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="orders-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'customer_name',
            'address',
            'description',
        ],
    ]) ?>

</div>